services:
    mssql:
        image: chriseaton/adventureworks:latest
        restart: always
        environment:
          SA_PASSWORD: 'MSSQLServer@2019'
          ACCEPT_EULA: 'Y'
        ports:
          - '1433:1433'
        volumes:
          - ./mssql:/var/lib/mssql
    iris:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      environment:
        - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      ports:
        - 41773:1972
        - 42773:52773
      volumes:
        - ./:/home/irisowner/dev
        - ./jdbc:/opt/irisbuild/jdbc
