    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")
	;; setup SQLgateway to mysql 
    set gty=##class(%SQLConnection).%New()
    set gty.Name="mysql"
    set gty.driver="com.mysql.cj.jdbc.Driver"
    set gty.Usr="user"
    set gty.pwd="password"
    set gty.URL="jdbc:mysql://mysql:3306/db"
    set gty.classpath="/opt/irisbuild/jdbc/mysql-connector-j-9.7.0.jar"
    set gty.isJDBC=1
    set sc=gty.%Save()
    ZWRITE gty,sc	
    ;;
    zn "USER"
    halt
